src/main/java/edu/uchicago/dayj/entities/Submit.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.uchicago.dayj.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author aK V
 */
@Entity
@Table(name = "SUBMIT")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Submit.findAll", query = "SELECT s FROM Submit s"),
    @NamedQuery(name = "Submit.findByTeamId", query = "SELECT s FROM Submit s WHERE s.teamId = :teamId"),
    @NamedQuery(name = "Submit.findByMessage", query = "SELECT s FROM Submit s WHERE s.message = :message"),
    @NamedQuery(name = "Submit.findByTotal", query = "SELECT s FROM Submit s WHERE s.total = :total")})
public class Submit implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "TEAM_ID")
    private Integer teamId;
    @Size(max = 255)
    @Column(name = "MESSAGE")
    private String message;
    @Size(max = 255)
    @Column(name = "TOTAL")
    private String total;

    public Submit() {
    }

    public Submit(Integer teamId) {
        this.teamId = teamId;
    }

    public Integer getTeamId() {
        return teamId;
    }

    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getTotal() {
        return total;
    }

    public void setTotal(String total) {
        this.total = total;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (teamId != null ? teamId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Submit)) {
            return false;
        }
        Submit other = (Submit) object;
        if ((this.teamId == null && other.teamId != null) || (this.teamId != null && !this.teamId.equals(other.teamId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "edu.uchicago.dayj.entities.Submit[ teamId=" + teamId + " ]";
    }
    
    
}

src/main/java/edu/uchicago/dayj/jsf/SubmitController.java
package edu.uchicago.dayj.jsf;

import edu.uchicago.dayj.entities.Submit;
import edu.uchicago.dayj.jsf.util.JsfUtil;
import edu.uchicago.dayj.jsf.util.PaginationHelper;
import edu.uchicago.dayj.beans.SubmitFacade;

import java.io.Serializable;
import java.util.Random;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("submitController")
@SessionScoped
public class SubmitController implements Serializable {

    private Submit current;
    private DataModel items = null;
    @EJB
    private edu.uchicago.dayj.beans.SubmitFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public SubmitController() {
    }

    public Submit getSelected() {
        if (current == null) {
            current = new Submit();
            selectedItemIndex = -1;
        }
        return current;
    }

    private SubmitFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Submit) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Submit();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            Random rand = new Random();
            int randomNum = rand.nextInt((100 - 1) + 1) + 1;
            current.setTeamId(678);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("SubmitCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Submit) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("SubmitUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Submit) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("SubmitDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Submit getSubmit(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Submit.class)
    public static class SubmitControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            SubmitController controller = (SubmitController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "submitController");
            return controller.getSubmit(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Submit) {
                Submit o = (Submit) object;
                return getStringKey(o.getTeamId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Submit.class.getName());
            }
        }

    }

}

src/main/webapp/submit/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateSubmitTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateSubmitLabel_teamId}" for="teamId" />
                    <h:inputText id="teamId" value="#{submitController.selected.teamId}" title="#{bundle.CreateSubmitTitle_teamId}" required="true" requiredMessage="#{bundle.CreateSubmitRequiredMessage_teamId}"/>
                    <h:outputLabel value="#{bundle.CreateSubmitLabel_message}" for="message" />
                    <h:inputText id="message" value="#{submitController.selected.message}" title="#{bundle.CreateSubmitTitle_message}" />
                    <h:outputLabel value="#{bundle.CreateSubmitLabel_total}" for="total" />
                    <h:inputText id="total" value="#{submitController.selected.total}" title="#{bundle.CreateSubmitTitle_total}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{submitController.create}" value="#{bundle.CreateSubmitSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{submitController.prepareList}" value="#{bundle.CreateSubmitShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateSubmitIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/submit/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditSubmitTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditSubmitLabel_teamId}" for="teamId" />
                    <h:inputText id="teamId" value="#{submitController.selected.teamId}" title="#{bundle.EditSubmitTitle_teamId}" required="true" requiredMessage="#{bundle.EditSubmitRequiredMessage_teamId}"/>
                    <h:outputLabel value="#{bundle.EditSubmitLabel_message}" for="message" />
                    <h:inputText id="message" value="#{submitController.selected.message}" title="#{bundle.EditSubmitTitle_message}" />
                    <h:outputLabel value="#{bundle.EditSubmitLabel_total}" for="total" />
                    <h:inputText id="total" value="#{submitController.selected.total}" title="#{bundle.EditSubmitTitle_total}" />
                </h:panelGrid>
                <h:commandLink action="#{submitController.update}" value="#{bundle.EditSubmitSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditSubmitViewLink}"/>
                <br />
                <h:commandLink action="#{submitController.prepareList}" value="#{bundle.EditSubmitShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditSubmitIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/submit/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListSubmitTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListSubmitEmpty}" rendered="#{submitController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{submitController.items.rowCount > 0}">
                    <h:outputText value="#{submitController.pagination.pageFirstItem + 1}..#{submitController.pagination.pageLastItem + 1}/#{submitController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{submitController.previous}" value="#{bundle.Previous} #{submitController.pagination.pageSize}" rendered="#{submitController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{submitController.next}" value="#{bundle.Next} #{submitController.pagination.pageSize}" rendered="#{submitController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{submitController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSubmitTitle_teamId}"/>
                            </f:facet>
                            <h:outputText value="#{item.teamId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSubmitTitle_message}"/>
                            </f:facet>
                            <h:outputText value="#{item.message}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSubmitTitle_total}"/>
                            </f:facet>
                            <h:outputText value="#{item.total}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{submitController.prepareView}" value="#{bundle.ListSubmitViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{submitController.prepareEdit}" value="#{bundle.ListSubmitEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{submitController.destroy}" value="#{bundle.ListSubmitDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{submitController.prepareCreate}" value="#{bundle.ListSubmitCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListSubmitIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/submit/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewSubmitTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewSubmitLabel_teamId}"/>
                    <h:outputText value="#{submitController.selected.teamId}" title="#{bundle.ViewSubmitTitle_teamId}"/>
                    <h:outputText value="#{bundle.ViewSubmitLabel_message}"/>
                    <h:outputText value="#{submitController.selected.message}" title="#{bundle.ViewSubmitTitle_message}"/>
                    <h:outputText value="#{bundle.ViewSubmitLabel_total}"/>
                    <h:outputText value="#{submitController.selected.total}" title="#{bundle.ViewSubmitTitle_total}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{submitController.destroyAndView}" value="#{bundle.ViewSubmitDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewSubmitEditLink}"/>
                <br />
                <h:commandLink action="#{submitController.prepareCreate}" value="#{bundle.ViewSubmitCreateLink}" />
                <br />
                <h:commandLink action="#{submitController.prepareList}" value="#{bundle.ViewSubmitShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewSubmitIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>